clear;
clc;

NG=200;
NS=10^3;
Av=[0:84];
ACg=[0 4;5 17;18 49;50 64;65 84;0 64];
[Filtered_Output_All,Filtered_Output_Large_Winter,Filtered_Output_Large_Summer] = Filter_Peaks(NG,NS,Av,ACg);

save('Filtered_Outputs.mat','Filtered_Output_All','Filtered_Output_Large_Winter','Filtered_Output_Large_Summer');

Scenario_Calculations(Filtered_Output_All.Continual_Booster.Low_Coverage,'All_Low_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_All.Continual_Booster.High_Coverage,'All_High_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_All.Annual_Booster.Low_Coverage,'All_Low_Coverage_Annual_Booster');
Scenario_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,'All_High_Coverage_Annual_Booster');

Scenario_Calculations(Filtered_Output_Large_Winter.Continual_Booster.Low_Coverage,'Large_Winter_Low_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_Large_Winter.Continual_Booster.High_Coverage,'Large_Winter_High_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_Large_Winter.Annual_Booster.Low_Coverage,'Large_Winter_Low_Coverage_Annual_Booster');
Scenario_Calculations(Filtered_Output_Large_Winter.Annual_Booster.High_Coverage,'Large_Winter_High_Coverage_Annual_Booster');

Scenario_Calculations(Filtered_Output_Large_Summer.Continual_Booster.Low_Coverage,'Large_Summer_Low_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_Large_Summer.Continual_Booster.High_Coverage,'Large_Summer_High_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_Large_Summer.Annual_Booster.Low_Coverage,'Large_Summer_Low_Coverage_Annual_Booster');
Scenario_Calculations(Filtered_Output_Large_Summer.Annual_Booster.High_Coverage,'Large_Summer_High_Coverage_Annual_Booster');


Comparison_Calculations(Filtered_Output_All.Continual_Booster.High_Coverage,Filtered_Output_All.Continual_Booster.Low_Coverage,'All_Alt-High_Coverage_Continual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,Filtered_Output_All.Continual_Booster.Low_Coverage,'All_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.Low_Coverage,Filtered_Output_All.Continual_Booster.Low_Coverage,'All_Alt-Low_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,Filtered_Output_All.Continual_Booster.High_Coverage,'All_Alt-High_Coverage_Annual_Booster_Baseline-High_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,Filtered_Output_All.Annual_Booster.Low_Coverage,'All_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Annual_Booster');

Comparison_Calculations(Filtered_Output_Large_Winter.Continual_Booster.High_Coverage,Filtered_Output_Large_Winter.Continual_Booster.Low_Coverage,'Large_Winter_Alt-High_Coverage_Continual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Winter.Annual_Booster.High_Coverage,Filtered_Output_Large_Winter.Continual_Booster.Low_Coverage,'Large_Winter_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Winter.Annual_Booster.Low_Coverage,Filtered_Output_Large_Winter.Continual_Booster.Low_Coverage,'Large_Winter_Alt-Low_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Winter.Annual_Booster.High_Coverage,Filtered_Output_Large_Winter.Continual_Booster.High_Coverage,'Large_Winter_Alt-High_Coverage_Annual_Booster_Baseline-High_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Winter.Annual_Booster.High_Coverage,Filtered_Output_Large_Winter.Annual_Booster.Low_Coverage,'Large_Winter_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Annual_Booster');

Comparison_Calculations(Filtered_Output_Large_Summer.Continual_Booster.High_Coverage,Filtered_Output_Large_Summer.Continual_Booster.Low_Coverage,'Large_Summer_Alt-High_Coverage_Continual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Summer.Annual_Booster.High_Coverage,Filtered_Output_Large_Summer.Continual_Booster.Low_Coverage,'Large_Summer_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Summer.Annual_Booster.Low_Coverage,Filtered_Output_Large_Summer.Continual_Booster.Low_Coverage,'Large_Summer_Alt-Low_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Summer.Annual_Booster.High_Coverage,Filtered_Output_Large_Summer.Continual_Booster.High_Coverage,'Large_Summer_Alt-High_Coverage_Annual_Booster_Baseline-High_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_Large_Summer.Annual_Booster.High_Coverage,Filtered_Output_Large_Summer.Annual_Booster.Low_Coverage,'Large_Summer_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Annual_Booster');
