clear;
clc;

NG=200;
NS=10^3;
Av=[0:84];
ACg=[0 4; 5 12;13 17; 18 49; 50 64; 65 85];
[Filtered_Output_All] = Filter_Unimodal_Peak_Winter(NG,NS,Av,ACg);

save('Filtered_Outputs_Unimodal_Winter.mat','Filtered_Output_All');

Scenario_Calculations(Filtered_Output_All.Continual_Booster.Low_Coverage,'Winter_Unimodal_Low_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_All.Continual_Booster.High_Coverage,'Winter_Unimodal_High_Coverage_Continual_Booster');
Scenario_Calculations(Filtered_Output_All.Annual_Booster.Low_Coverage,'Winter_Unimodal_Low_Coverage_Annual_Booster');
Scenario_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,'Winter_Unimodal_High_Coverage_Annual_Booster');


Comparison_Calculations(Filtered_Output_All.Continual_Booster.High_Coverage,Filtered_Output_All.Continual_Booster.Low_Coverage,'Winter_Unimodal_Alt-High_Coverage_Continual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,Filtered_Output_All.Continual_Booster.Low_Coverage,'Winter_Unimodal_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.Low_Coverage,Filtered_Output_All.Continual_Booster.Low_Coverage,'Winter_Unimodal_Alt-Low_Coverage_Annual_Booster_Baseline-Low_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,Filtered_Output_All.Continual_Booster.High_Coverage,'Winter_Unimodal_Alt-High_Coverage_Annual_Booster_Baseline-High_Coverage_Continual_Booster');
Comparison_Calculations(Filtered_Output_All.Annual_Booster.High_Coverage,Filtered_Output_All.Annual_Booster.Low_Coverage,'Winter_Unimodal_Alt-High_Coverage_Annual_Booster_Baseline-Low_Coverage_Annual_Booster');