clear;
clc;

Av=[0:84];
ACg=[0 4; 5 12;13 17; 18 49; 50 64; 65 85];

SA_Scenario={'Annual_Campaign_Influenza_Like_Coverage'};%,'Annual_Campaign_Baseline_Coverage','Two_Campaign_Influenza_Like_Coverage_90_days_65_and_older','Two_Campaign_Influenza_Like_Coverage_120_days_65_and_older','Two_Campaign_Influenza_Like_Coverage_150_days_65_and_older','Two_Campaign_Influenza_Like_Coverage_180_days_65_and_older','Two_Campaign_Baseline_Coverage_90_days_65_and_older','Two_Campaign_Baseline_Coverage_120_days_65_and_older','Two_Campaign_Baseline_Coverage_150_days_65_and_older','Two_Campaign_Baseline_Coverage_180_days_65_and_older','Annual_Campaign_Influenza_Like_Coverage_Indirect_10000_Additional_Doses_Ages_0_to_4','Annual_Campaign_Influenza_Like_Coverage_Indirect_10000_Additional_Doses_Ages_5_to_12','Annual_Campaign_Influenza_Like_Coverage_Indirect_10000_Additional_Doses_Ages_13_to_17','Annual_Campaign_Influenza_Like_Coverage_Indirect_10000_Additional_Doses_Ages_18_to_49','Annual_Campaign_Influenza_Like_Coverage_Indirect_10000_Additional_Doses_Ages_50_to_64','Annual_Campaign_Influenza_Like_Coverage_Indirect_10000_Additional_Doses_Ages_65_to_84'};

for ss=1:length(SA_Scenario)
    [Filtered_Output_All,Filtered_Output_Large_Winter,Filtered_Output_Large_Summer] = SA_Output(SA_Scenario{ss},Av,ACg);
    save(['Output_SA_' SA_Scenario{ss} '.mat'],'Filtered_Output_All','Filtered_Output_Large_Winter','Filtered_Output_Large_Summer');
end