function [Filtered_Output_All]=Output_Peak_Filter_Unimodal_Winter(Filtered_Output_All,Peaks)

Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence=Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Burden=Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Burden(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Admission=Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Admission(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Death=Filtered_Output_All.Annual_Booster.Low_Coverage.Death(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence_Cumulative_Count=Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Cumulative_Count=Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Death_Cumulative_Count=Filtered_Output_All.Annual_Booster.Low_Coverage.Death_Cumulative_Count(Peaks==1,:);

Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence=Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Burden=Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Burden(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Admission=Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Admission(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Death=Filtered_Output_All.Continual_Booster.Low_Coverage.Death(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence_Cumulative_Count=Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Cumulative_Count=Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Death_Cumulative_Count=Filtered_Output_All.Continual_Booster.Low_Coverage.Death_Cumulative_Count(Peaks==1,:);

Filtered_Output_All.Annual_Booster.High_Coverage.Incidence=Filtered_Output_All.Annual_Booster.High_Coverage.Incidence(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Burden=Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Burden(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Admission=Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Admission(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Death=Filtered_Output_All.Annual_Booster.High_Coverage.Death(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Incidence_Cumulative_Count=Filtered_Output_All.Annual_Booster.High_Coverage.Incidence_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Cumulative_Count=Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Death_Cumulative_Count=Filtered_Output_All.Annual_Booster.High_Coverage.Death_Cumulative_Count(Peaks==1,:);

Filtered_Output_All.Continual_Booster.High_Coverage.Incidence=Filtered_Output_All.Continual_Booster.High_Coverage.Incidence(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Burden=Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Burden(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Admission=Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Admission(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Death=Filtered_Output_All.Continual_Booster.High_Coverage.Death(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Incidence_Cumulative_Count=Filtered_Output_All.Continual_Booster.High_Coverage.Incidence_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Cumulative_Count=Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Cumulative_Count(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Death_Cumulative_Count=Filtered_Output_All.Continual_Booster.High_Coverage.Death_Cumulative_Count(Peaks==1,:);

Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence_Cumulative_Count_Age=Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Death_Cumulative_Count_Age=Filtered_Output_All.Annual_Booster.Low_Coverage.Death_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Cumulative_Count_Age=Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Cumulative_Count_Age(Peaks==1,:);

Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence_Cumulative_Count_Age=Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Death_Cumulative_Count_Age=Filtered_Output_All.Continual_Booster.Low_Coverage.Death_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Cumulative_Count_Age=Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Cumulative_Count_Age(Peaks==1,:);

Filtered_Output_All.Annual_Booster.High_Coverage.Incidence_Cumulative_Count_Age=Filtered_Output_All.Annual_Booster.High_Coverage.Incidence_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Death_Cumulative_Count_Age=Filtered_Output_All.Annual_Booster.High_Coverage.Death_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Cumulative_Count_Age=Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Cumulative_Count_Age(Peaks==1,:);

Filtered_Output_All.Continual_Booster.High_Coverage.Incidence_Cumulative_Count_Age=Filtered_Output_All.Continual_Booster.High_Coverage.Incidence_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Death_Cumulative_Count_Age=Filtered_Output_All.Continual_Booster.High_Coverage.Death_Cumulative_Count_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Cumulative_Count_Age=Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Cumulative_Count_Age(Peaks==1,:);

Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence_Cumulative_Count_Compliment_Age=Filtered_Output_All.Annual_Booster.Low_Coverage.Incidence_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Death_Cumulative_Count_Compliment_Age=Filtered_Output_All.Annual_Booster.Low_Coverage.Death_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Cumulative_Count_Compliment_Age=Filtered_Output_All.Annual_Booster.Low_Coverage.Hospital_Cumulative_Count_Compliment_Age(Peaks==1,:);

Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence_Cumulative_Count_Compliment_Age=Filtered_Output_All.Continual_Booster.Low_Coverage.Incidence_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Death_Cumulative_Count_Compliment_Age=Filtered_Output_All.Continual_Booster.Low_Coverage.Death_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Cumulative_Count_Compliment_Age=Filtered_Output_All.Continual_Booster.Low_Coverage.Hospital_Cumulative_Count_Compliment_Age(Peaks==1,:);

Filtered_Output_All.Annual_Booster.High_Coverage.Incidence_Cumulative_Count_Compliment_Age=Filtered_Output_All.Annual_Booster.High_Coverage.Incidence_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Death_Cumulative_Count_Compliment_Age=Filtered_Output_All.Annual_Booster.High_Coverage.Death_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Cumulative_Count_Compliment_Age=Filtered_Output_All.Annual_Booster.High_Coverage.Hospital_Cumulative_Count_Compliment_Age(Peaks==1,:);

Filtered_Output_All.Continual_Booster.High_Coverage.Incidence_Cumulative_Count_Compliment_Age=Filtered_Output_All.Continual_Booster.High_Coverage.Incidence_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Death_Cumulative_Count_Compliment_Age=Filtered_Output_All.Continual_Booster.High_Coverage.Death_Cumulative_Count_Compliment_Age(Peaks==1,:);
Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Cumulative_Count_Compliment_Age=Filtered_Output_All.Continual_Booster.High_Coverage.Hospital_Cumulative_Count_Compliment_Age(Peaks==1,:);
end